language: node_js
node_js:
  - "10"
before_script:
  - npx version-from-git --travis --no-git-tag-version
  - npm run bootstrap
  - node scripts/syncVersion
  - npm run build
before_deploy:
  - cp -r packages/component/lib .
deploy:
  - provider: npm
    api_key:
      secure: "GwDa8lQLg5gCrs4VZJ2AULFWnYPRJZ7HTyptZK6KzH9CFMCO/iuhn3q7vlaqN4bBD5HMfcjfzO6Sv/9lYIn7VcIJn+OwCk4SNHNTfDaGxOGfKr5XmPWfcortmxA99q8EHnIQZmxyV2ejgGxXwhkL5HybwdvAOF0kGDYuiviTWwtCeuCKeG0rZCsp9DZafzgJXffxvrkRGAqX02tNEnHo4yf9QBkYFdR+QvAyKPWSlajamuJnYt3clwaLt11/842Sk3fuYjn3E12enketOlmi91kHeV8/UCGNeMoJwQXCdBmKwC9weIMecXijriT5tXRox4eKxgcrRAxwiqb+Rm87RK4j5rDRrTThP77XjmhE+BKbRkwrpc8pZdRX4YCtmFj1vK0/kJPXUmYAx9YbKZahpd0UWJs76wjDHqF6r/criL8jMjA+FR2ne5PxQJTK9VPT+dfYwnLdFtmn1XbluZXo/PeKpsorWAWhO5QObEY3K5pMrhZWN8elXANI7CgI2EGrfdqhHEnvGupHF2C77wJETjvz8q38cBhmJbj3kDXmvPRVQ/3qTteetWvHtyThqwBhvaUa1IYrKAOy+ubpmpYNM4Kyu9znmrTEHye/d867zY8MeeYNcIx7TR4aou+B8NIrkbGfK8L64AqURIiMnSJ2gaHNuXUedcuM2XqoubZ4ZaI="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "GwDa8lQLg5gCrs4VZJ2AULFWnYPRJZ7HTyptZK6KzH9CFMCO/iuhn3q7vlaqN4bBD5HMfcjfzO6Sv/9lYIn7VcIJn+OwCk4SNHNTfDaGxOGfKr5XmPWfcortmxA99q8EHnIQZmxyV2ejgGxXwhkL5HybwdvAOF0kGDYuiviTWwtCeuCKeG0rZCsp9DZafzgJXffxvrkRGAqX02tNEnHo4yf9QBkYFdR+QvAyKPWSlajamuJnYt3clwaLt11/842Sk3fuYjn3E12enketOlmi91kHeV8/UCGNeMoJwQXCdBmKwC9weIMecXijriT5tXRox4eKxgcrRAxwiqb+Rm87RK4j5rDRrTThP77XjmhE+BKbRkwrpc8pZdRX4YCtmFj1vK0/kJPXUmYAx9YbKZahpd0UWJs76wjDHqF6r/criL8jMjA+FR2ne5PxQJTK9VPT+dfYwnLdFtmn1XbluZXo/PeKpsorWAWhO5QObEY3K5pMrhZWN8elXANI7CgI2EGrfdqhHEnvGupHF2C77wJETjvz8q38cBhmJbj3kDXmvPRVQ/3qTteetWvHtyThqwBhvaUa1IYrKAOy+ubpmpYNM4Kyu9znmrTEHye/d867zY8MeeYNcIx7TR4aou+B8NIrkbGfK8L64AqURIiMnSJ2gaHNuXUedcuM2XqoubZ4ZaI="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: "umaU6rQk6JmPx+4Eg1/04rsPWFsUqcK01feQyyhYiXbH3/Db4rNskX+jN+yoCjYi/sAdC5yYZSyqjzGuIOUbM5S3VUEKyZ93/2GIPv5CBp5zigLJ3JZRbJgqtzi52+MaKe2nSCU97V69+J9lFbkpFElhf/xC/oAFDUg89rhvGM+ICsy1pVJXWYErmoXot04vqIM8S9luFF/73NlqlwV+I+UYjiT8e9rBFdfEaHBhO+VQpY/uo1BuRU5A57AfmjxsRvNUd2sChi2rSBY1ief2fO1+CSuMCAHhvxu10V5y/SkY6FZoBzQnAz/q8rkAtYGLC9+RAZcGCl6VggYcL1MODv3hUhioSr0ZQ0xWeiYuc6J2TdqI1+wkfe5+DffPOO6GyCIe2GNM2zD9WST4WiKIt3cu/N2vBEYCEz/kcrX+6wNyQWpZHvTNynlJXOdd17u8ctT3RRwz+kSwLDvc0ZpXc/CVbeLgXl+Sh3AX18b+NEfJat+ZpWTdblWUOds4BczA8LhXMYF65HIRX8eQci1JtQC0V+Tua8LBGlpzSeXIE+VzgvvZRHStaGB4yZtZJV/pshP0ng/xFMrkt3/ZZC2UpqZOSiFUsBrseYvCvRJHOLJwWG1gk5GjsdHikKBvOBbGvsfdFhSfxGyvhKgPRkS+yQ7K2aLgbVVSApmcQkWpDes="
    on:
      branch: master
    local-dir: packages/playground/build
  - provider: releases
    api_key:
      secure: "umaU6rQk6JmPx+4Eg1/04rsPWFsUqcK01feQyyhYiXbH3/Db4rNskX+jN+yoCjYi/sAdC5yYZSyqjzGuIOUbM5S3VUEKyZ93/2GIPv5CBp5zigLJ3JZRbJgqtzi52+MaKe2nSCU97V69+J9lFbkpFElhf/xC/oAFDUg89rhvGM+ICsy1pVJXWYErmoXot04vqIM8S9luFF/73NlqlwV+I+UYjiT8e9rBFdfEaHBhO+VQpY/uo1BuRU5A57AfmjxsRvNUd2sChi2rSBY1ief2fO1+CSuMCAHhvxu10V5y/SkY6FZoBzQnAz/q8rkAtYGLC9+RAZcGCl6VggYcL1MODv3hUhioSr0ZQ0xWeiYuc6J2TdqI1+wkfe5+DffPOO6GyCIe2GNM2zD9WST4WiKIt3cu/N2vBEYCEz/kcrX+6wNyQWpZHvTNynlJXOdd17u8ctT3RRwz+kSwLDvc0ZpXc/CVbeLgXl+Sh3AX18b+NEfJat+ZpWTdblWUOds4BczA8LhXMYF65HIRX8eQci1JtQC0V+Tua8LBGlpzSeXIE+VzgvvZRHStaGB4yZtZJV/pshP0ng/xFMrkt3/ZZC2UpqZOSiFUsBrseYvCvRJHOLJwWG1gk5GjsdHikKBvOBbGvsfdFhSfxGyvhKgPRkS+yQ7K2aLgbVVSApmcQkWpDes="
    on:
      tags: true
    skip_cleanup: true
