name: Bump scaffold

on:
  workflow_dispatch:
    inputs:
      package-name:
        default: react-dictate-button
        description: Name of the package
        required: true
        type: string
      use-react:
        default: true
        description: Use React
        required: true
        type: boolean
      skip-integration-test:
        default: false
        description: Skip integration test
        required: true
        type: boolean

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
    secrets:
      APP_ID: ${{ secrets.WORKFLOW_BOT_APP_ID }}
      PRIVATE_KEY: ${{ secrets.WORKFLOW_BOT_PRIVATE_KEY }}
    uses: compulim/workflows/.github/workflows/bump-scaffold.yml@main
    with:
      package-name: ${{ inputs.package-name }}
      skip-integration-test: ${{ inputs.skip-integration-test }}
      use-react: ${{ inputs.use-react }}
